
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: stefanmr
      MYSQL_DATABASE: java_web
      MYSQL_USER: root
      MYSQL_PASSWORD: stefanmr
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/java_web
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: stefanmr
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
